<?php

return array(
  'metabase_url' => array(
    'group_name' => 'Metasearch settings',
    'group' => 'metasearch',
    'name' => 'metabase_url',
    'type' => 'String',
    'quick_form_type' => 'Element',
    'html_type' => 'text',
    'default' => 'https://metabase.example.com',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Metabase Root URL',
    'description' => "Metabase root URL",
    'help_text' => "Metabase root URL",
  ),
  'metabase_user' => array(
    'group_name' => 'Metasearch settings',
    'group' => 'metasearch',
    'name' => 'metabase_user',
    'type' => 'String',
    'quick_form_type' => 'Element',
    'html_type' => 'text',
    'default' => 'user@example.com',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Metabase user',
    'description' => "Metabase user",
    'help_text' => "Metabase user",
  ),
  'metabase_password' => array(
    'group_name' => 'Metasearch settings',
    'group' => 'metasearch',
    'name' => 'metabase_password',
    'type' => 'String',
    'quick_form_type' => 'Element',
    'html_type' => 'password',
    'default' => '',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Metabase password',
    'description' => "Metabase password",
    'help_text' => "Metabase password",
  ),
);
